#!/bin/bash
set -e

# if this fails, please run mvn prettier:write to reformat
echo '[pre-commit] Prettier check the code format "mvn prettier:check" ...'
if ! mvn -q prettier:check; then
  echo_r "\n[ERROR] Prettier check failed."
  echo -e "Please run \"mvn prettier:write\" to reformat\n"
  exit 1
fi

# if this fails, please run mvn ktlint:format to reformat
echo '[pre-commit] Ktlint check the code format "mvn ktlint:check" ...'
if ! mvn -q ktlint:check; then
  echo_r "\n[ERROR] format check failed."
  echo -e "Please run \"mvn ktlint:format\" to reformat\n"
  exit 1
fi

echo "[pre-commit] Java and Kotlin code format check ok"
